ALTER TABLE invoice_payments
ADD COLUMN IF NOT EXISTS is_voided BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE invoice_payments
ADD COLUMN IF NOT EXISTS voided_at TIMESTAMPTZ;

ALTER TABLE invoice_payments
ADD COLUMN IF NOT EXISTS voided_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE invoice_payments
ADD COLUMN IF NOT EXISTS void_reason TEXT;
