package warehouse_receipt

import "errors"

var (
	ErrReceiptStoreIDRequired        = errors.New("store_id is required")
	ErrReceiptStoreContextRequired   = errors.New("store context is required")
	ErrReceiptWarehouseRequired      = errors.New("warehouse_id is required")
	ErrReceiptNotFound               = errors.New("warehouse receipt not found")
	ErrReceiptForbidden              = errors.New("user cannot operate this store")
	ErrReceiptConfirmForbidden       = errors.New("user cannot confirm this warehouse receipt")
	ErrReceiptCancelForbidden        = errors.New("user cannot cancel this warehouse receipt")
	ErrReceiptImmutable              = errors.New("only draft warehouse receipt can be modified")
	ErrReceiptCancelOnlyDraft        = errors.New("only draft warehouse receipt can be cancelled")
	ErrReceiptConfirmOnlyDraft       = errors.New("only draft warehouse receipt can be confirmed")
	ErrReceiptInvalidStatus          = errors.New("invalid warehouse receipt status")
	ErrInvalidPagination             = errors.New("invalid pagination query")
	ErrReceiptDocumentNoRequired     = errors.New("document_no is required")
	ErrReceiptDuplicateDocumentNo    = errors.New("document_no already exists")
	ErrReceiptInvalidVATPercent      = errors.New("vat_percent must be between 0 and 100")
	ErrReceiptItemsRequired          = errors.New("at least one receipt item is required")
	ErrReceiptItemNotFound           = errors.New("warehouse receipt item not found")
	ErrReceiptItemQuantityRequired   = errors.New("quantity must be greater than or equal to 1")
	ErrReceiptItemUnitPriceInvalid   = errors.New("unit_price must be greater than or equal to zero")
	ErrReceiptItemLocationRequired   = errors.New("location_id is required")
	ErrReceiptItemProductRequired    = errors.New("product_id is required")
	ErrReceiptDuplicateItem          = errors.New("duplicate product and location combination is not allowed")
	ErrReceiptLocationNotFound       = errors.New("location not found")
	ErrReceiptLocationInactive       = errors.New("location is inactive")
	ErrReceiptLocationWrongStore     = errors.New("location does not belong to this store")
	ErrReceiptLocationWrongWarehouse = errors.New("location does not belong to receipt warehouse")
	ErrReceiptLocationSalePoint      = errors.New("sale point locations cannot be used for warehouse receipts")
	ErrReceiptWarehouseNotFound      = errors.New("warehouse not found")
	ErrReceiptSupplierNotFound       = errors.New("supplier not found")
	ErrReceiptPurchaseOrderNotFound  = errors.New("purchase order not found")
	ErrReceiptProductNotFound        = errors.New("product not found")
	ErrReceiptProductInactive        = errors.New("product is inactive")
	ErrReceiptAttachmentRequired     = errors.New("attachment file is required")
	ErrReceiptAttachmentType         = errors.New("attachment file type must be pdf, jpg, or png")
	ErrReceiptAttachmentSize         = errors.New("attachment file size must be less than or equal to 10MB")
	ErrReceiptAttachmentStorage      = errors.New("attachment storage is not configured")
	ErrReceiptAttachmentUploadFailed = errors.New("failed to upload receipt attachment")
	ErrReceiptPOQuantityExceeded     = errors.New("receipt quantity exceeds outstanding purchase order quantity")
)
